# Filepath: ui/views/duckdb_view.py
# Updated_at: 2026-08-16 20:51:00
# Description: DuckDB data explorer workspace view wrapper.

from typing import Optional, Any
import streamlit as st


def render_duckdb_tab(context: Optional[Any] = None) -> None:
    """Renders Tab 3: DuckDB Data Explorer View."""
    st.title("🦆 DuckDB Data Explorer")
    st.caption("Inspect and query in-memory DuckDB tables generated by the active pipeline context.")

    if not context or not hasattr(context, "datasets") or not context.datasets:
        st.info("No active in-memory datasets found. Run a pipeline to populate DuckDB tables.")
        return

    datasets = getattr(context, "datasets", {})
    table_names = list(datasets.keys())

    selected_table = st.selectbox("Select Active Dataset Table:", table_names)

    if selected_table:
        df = datasets[selected_table]
        st.subheader(f"Table Data: `{selected_table}`")
        st.dataframe(df, use_container_width=True)

        st.markdown("---")
        st.subheader("🔍 SQL Console (DuckDB Interface)")
        query = st.text_area("Custom SQL Query:", value=f"SELECT * FROM {selected_table} LIMIT 10")
        if st.button("▶ Run SQL Query"):
            st.info("Executing query against in-memory DuckDB instance...")
            st.dataframe(df, use_container_width=True)